# Generated by Django 5.2.16 on 2026-08-02 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('anonymous_session_id', models.CharField(db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('page_path', models.CharField(max_length=300)),
                ('cta_name', models.CharField(blank=True, max_length=120)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('attribution', models.JSONField(default=dict)),
                ('device_category', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=16)),
                ('consent_state', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('duplicate_fingerprint', models.CharField(db_index=True, editable=False, max_length=64)),
                ('full_name', models.CharField(max_length=160)),
                ('business_name', models.CharField(max_length=200)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=80)),
                ('preferred_language', models.CharField(max_length=40)),
                ('industry', models.CharField(max_length=100)),
                ('employee_count', models.CharField(max_length=40)),
                ('monthly_call_volume', models.CharField(max_length=40)),
                ('product_interest', models.CharField(max_length=120)),
                ('preferred_demo_date', models.DateField(blank=True, null=True)),
                ('preferred_demo_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField()),
                ('attribution', models.JSONField(default=dict)),
                ('landing_page_url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('cta_clicked', models.CharField(blank=True, max_length=120)),
                ('anonymous_session_id', models.CharField(db_index=True, max_length=64)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('delivery_reference', models.CharField(blank=True, max_length=128)),
                ('delivery_error_code', models.CharField(blank=True, max_length=64)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
