# Generated by Django 5.2.16 on 2026-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='cta_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='solution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='campaign_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='follow_up_sla_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='industry_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='lead_classification',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='lead_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='score_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='solution_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadsubmission',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], db_index=True, default='queued', max_length=16),
        ),
    ]
