# Generated by Django 5.2.16 on 2026-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0002_analyticsevent_cta_position_analyticsevent_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsubmission',
            name='assignment_queue',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='medium_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='source_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='team_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
