# Generated by Django 5.1.4 on 2025-02-07 13:00

import career_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=70, primary_key=True, serialize=False)),
                ('user_id', models.FileField(blank=True, null=True, upload_to='career/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='career/')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('primary_profession', models.CharField(blank=True, max_length=256, null=True)),
                ('project_link', models.CharField(blank=True, max_length=256, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='career_app.career')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text')], max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='career_app.career')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='career_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_options', models.ManyToManyField(blank=True, to='career_app.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='career_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='career_app.career')),
            ],
        ),
    ]
