"""
Django settings for CORE project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import json
from pathlib import Path
from decouple import config
from django.utils.timezone import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)
ENVIRONMENT = config("ENV", default="dev")

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    
    # Third party apps
    'drf_yasg',
    'corsheaders',
    'rest_framework',
    'django_celery_beat',
    'django_user_agents',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    # Local apps
    'blog_app',
    'auth_app',
    'employee',
    'calendar_app',
    'cms',
    'hero',
    'customers',
    'career_app',
    'payment_app',
    'lead_capture',
    'server_c',
    'sales_scraper',
]

# Server C is a presentation and request-preparation boundary. Privileged
# business mutations must fail closed unless the middleware gateway is set.
MIDDLEWARE_GATEWAY_URL = config("MIDDLEWARE_GATEWAY_URL", default="")
MIDDLEWARE_GATEWAY_TIMEOUT = config("MIDDLEWARE_GATEWAY_TIMEOUT", cast=float, default=8.0)
AI_GATEWAY_URL = config("AI_GATEWAY_URL", default="")
SERVER_C_PLATFORM_VERSION = config("SERVER_C_PLATFORM_VERSION", default="1.0")
SERVER_C_FEATURE_FLAGS = {
    "MARKETPLACE_STAGING_ENABLED": True,
    "MARKETPLACE_SEARCH_ENABLED": True,
    "MARKETPLACE_TRIAL_REQUESTS_ENABLED": True,
    "MARKETPLACE_INSTALLATION_REQUESTS_ENABLED": True,
    "AI_SALES_STAGING_ENABLED": True,
    "SCRAPER_STAGING_ENABLED": True,
    "LEAD_ENRICHMENT_ENABLED": True,
    "LEAD_SCORING_ENABLED": True,
    "CRM_SUBMISSION_REQUESTS_ENABLED": True,
    "PUBLIC_WEBSITE_ENABLED": True,
    "CUSTOMER_PORTAL_STAGING_ENABLED": True,
    "PARTNER_PORTAL_STAGING_ENABLED": True,
    "DEVELOPER_PORTAL_STAGING_ENABLED": True,
    "DOCUMENTATION_PORTAL_ENABLED": True,
    "ACADEMY_STAGING_ENABLED": True,
    "AUTOMATIC_MARKETPLACE_INSTALLATION_ENABLED": False,
    "AUTOMATIC_MARKETPLACE_PRODUCTION_ACTIVATION_ENABLED": False,
    "AUTOMATIC_PUBLICATION_ENABLED": False,
    "AUTONOMOUS_OUTREACH_ENABLED": False,
    "AUTONOMOUS_EMAIL_ENABLED": False,
    "AUTONOMOUS_SMS_ENABLED": False,
    "AUTONOMOUS_SOCIAL_MESSAGES_ENABLED": False,
    "DIRECT_ODOO_WRITES_ENABLED": False,
    "DIRECT_VICIDIAL_WRITES_ENABLED": False,
    "UNRESTRICTED_SCRAPING_ENABLED": False,
    "GLOBAL_PRODUCTION_ACTIVATION_ENABLED": False,
}

# The crawler is isolated and read-only with respect to every external system.
SCRAPER_WORKER_ENABLED = config("SCRAPER_WORKER_ENABLED", cast=bool, default=False)
SCRAPER_MIDDLEWARE_DELIVERY_ENABLED = config("SCRAPER_MIDDLEWARE_DELIVERY_ENABLED", cast=bool, default=False)
SCRAPER_DELIVERY_URL = config("SCRAPER_DELIVERY_URL", default="")
SCRAPER_DELIVERY_SCHEMA_CHECKSUM = config("SCRAPER_DELIVERY_SCHEMA_CHECKSUM", default="")
SCRAPER_DELIVERY_HMAC_KEY_ID = config("SCRAPER_DELIVERY_HMAC_KEY_ID", default="")
SCRAPER_DELIVERY_HMAC_SECRET = config("SCRAPER_DELIVERY_HMAC_SECRET", default="")
SCRAPER_DELIVERY_BEARER_TOKEN = config("SCRAPER_DELIVERY_BEARER_TOKEN", default="")
SCRAPER_DELIVERY_CA_BUNDLE = config("SCRAPER_DELIVERY_CA_BUNDLE", default="")
SCRAPER_DELIVERY_CLIENT_CERT = config("SCRAPER_DELIVERY_CLIENT_CERT", default="")
SCRAPER_DELIVERY_CONNECT_TIMEOUT = config("SCRAPER_DELIVERY_CONNECT_TIMEOUT", cast=float, default=3.0)
SCRAPER_DELIVERY_READ_TIMEOUT = config("SCRAPER_DELIVERY_READ_TIMEOUT", cast=float, default=8.0)
SCRAPER_DELIVERY_LEASE_SECONDS = config("SCRAPER_DELIVERY_LEASE_SECONDS", cast=int, default=60)
SCRAPER_DELIVERY_MAX_BACKOFF = config("SCRAPER_DELIVERY_MAX_BACKOFF", cast=int, default=300)
SCRAPER_DELIVERY_ACCEPTED_STATUSES = tuple(int(item) for item in config("SCRAPER_DELIVERY_ACCEPTED_STATUSES", default="202,208").split(","))
SCRAPER_DELIVERY_ACK_FIELD = config("SCRAPER_DELIVERY_ACK_FIELD", default="acknowledgement_id")
SCRAPER_ODOO_WRITES_ENABLED = False
SCRAPER_VICIDIAL_WRITES_ENABLED = False
SCRAPER_N8N_WRITES_ENABLED = False
SCRAPER_POSTLY_WRITES_ENABLED = False
SCRAPER_OUTREACH_WRITES_ENABLED = False

APPEND_SLASH = False

ASGI_APPLICATION = "CORE.asgi.application"
AUTH_USER_MODEL = 'auth_app.User'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = False

MIDDLEWARE = [
    
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    
    # custom middleware
    'middlewares.visitors_details_middleware.VisitorTrackingMiddleware',
    'middlewares.block_ip_address_middleware.BlockBlacklistedIPsMiddleware',
]

if ENVIRONMENT == "test":
    MIDDLEWARE = [item for item in MIDDLEWARE if not item.startswith("middlewares.")]

ROOT_URLCONF = 'CORE.urls'

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS", cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)

CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=lambda v: [s.strip() for s in v.split(',')])

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CORE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB"),
        "USER": config("POSTGRES_USER"),
        "PASSWORD": config("POSTGRES_PASS"),
        "HOST": config("PG_HOST"),
        "PORT": config("PG_PORT"),
    }
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_FROM = config("EMAIL_FROM", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=False)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)

EMAIL_VERIFICATION_URL = config("EMAIL_VERIFICATION_URL", default="")



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REDIS_CONNECTION_URL = config("REDIS_URL", default="redis://redis:6379/0")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CONNECTION_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

if ENVIRONMENT == "test":
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

USER_AGENTS_CACHE = 'default'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static') ]


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_ALLOW_NONIMAGE_FILES = True

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    "PAGE_SIZE": 10,
    'DEFAULT_PERMISSION_CLASSES': (
        'CORE.permissions.ReadOnlyOrAdmin',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '300/minute',
    },

}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

BASE_URL=config("BASE_URL", default="http://localhost:8000")

ADMIN_EMAIL = config("ADMIN_EMAIL", default="support@codestra.co")
EMAIL_FROM = config("EMAIL_FROM", default="sales@codestra.co")
STRIP_SECRET_KEY = config("STRIP_SECRET_KEY", default="")
STRIP_PUBLISHABLE_KEY = config("STRIP_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
WEBHOOK_STAGING_MODE = config("WEBHOOK_STAGING_MODE", default=False, cast=bool)
WEBHOOK_STAGING_SECRET = config("WEBHOOK_STAGING_SECRET", default="")

ODOO_BASE_URL = config("ODOO_BASE_URL", default="https://crm.codestra.co").rstrip("/")
ODOO_API_TOKEN = config("ODOO_API_TOKEN", default="")
ODOO_DATABASE = config("ODOO_DATABASE", default="")
ODOO_CLIENT_ID = config("ODOO_CLIENT_ID", default="")
ODOO_CLIENT_SECRET = config("ODOO_CLIENT_SECRET", default="")
ODOO_LEAD_MODEL = config("ODOO_LEAD_MODEL", default="crm.lead")
ODOO_DEFAULT_TEAM_ID = config("ODOO_DEFAULT_TEAM_ID", default="")
ODOO_DEFAULT_CAMPAIGN_ID = config("ODOO_DEFAULT_CAMPAIGN_ID", default="")
ODOO_REQUEST_TIMEOUT_MS = config("ODOO_REQUEST_TIMEOUT_MS", default=8000, cast=int)
ODOO_FIELD_MAPPING_CONFIRMED = config("ODOO_FIELD_MAPPING_CONFIRMED", default=False, cast=bool)
ODOO_ROUTING_MAP = json.loads(config("ODOO_ROUTING_MAP", default="{}"))
LEAD_DELIVERY_MODE = config("LEAD_DELIVERY_MODE", default="mock")
PUBLIC_DEMO_PHONE = config("PUBLIC_DEMO_PHONE", default="")
PUBLIC_SALES_PHONE = config("PUBLIC_SALES_PHONE", default="")
PUBLIC_SITE_URL = config("PUBLIC_SITE_URL", default="https://codestra.co")
INTERNAL_SERVICE_SECRET = config("INTERNAL_SERVICE_SECRET", default="")
INTERNAL_SERVICE_ALLOWLIST = [item.strip() for item in config("INTERNAL_SERVICE_ALLOWLIST", default="").split(",") if item.strip()]

REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"].update({
    "lead_submission": "10/hour",
    "analytics_event": "120/minute",
})

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/1")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/2")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
