import type { IndustryConfig } from "./industryConfig";

type Expansion = Omit<IndustryConfig, "problems" | "integrations" | "scenarios" | "faq" | "routing"> & {
  routing?: string[];
};

const build = (config: Expansion): IndustryConfig => ({
  ...config,
  problems: [
    `${config.name} inquiries arrive across disconnected channels`,
    "Teams repeat intake and status work that can follow approved rules",
    "Important requests lose context during handoffs",
    "Campaign and operational outcomes are difficult to measure",
  ],
  routing: config.routing ?? ["Qualified service team", "Operations", "Sales or support", "Urgent human escalation"],
  integrations: [
    { name: "Odoo CRM", status: "Supported" },
    { name: "n8n", status: "Supported" },
    { name: "Industry systems", status: "Planned" },
  ],
  scenarios: [
    { title: "New inquiry", transcript: `A visitor asks about ${(config.products?.[0] ?? config.name).toLowerCase()} and provides approved intake details.`, outcome: "Qualified request prepared for the correct team." },
    { title: "Scheduled follow-up", transcript: "The visitor selects a preferred time, language, and contact method.", outcome: "Follow-up activity queued with complete context." },
    { title: "Human escalation", transcript: "The request reaches a restricted action or requires professional judgment.", outcome: "Authorized employee receives the conversation context." },
  ],
  faq: [
    ["Can Codestra work with our current systems?", "Yes. Each connection is confirmed, mapped, and tested before activation."],
    ["Does the AI replace professional judgment?", "No. Restricted and consequential decisions remain with authorized people."],
    ["Can it update Odoo?", "Only through the controlled backend after field, campaign, team, and access validation in staging."],
    ["Can we test before launch?", "Yes. Intake, routing, failures, retries, escalation, and rollback should be rehearsed first."],
    ["Are the demonstrations real customer activity?", "No. Demonstrations and dashboard values are clearly labeled simulations or sample data."],
  ],
});

export const expansionIndustryConfigs: IndustryConfig[] = [
  build({slug:"education-ai",campaign:"EDUCATION_AI",name:"Education and training",category:"Public and Community Services",eyebrow:"AI for Education and Training",headline:"Support Every Student From Enrollment to Completion",summary:"Connect admissions, registration, student support, parent communication, training, reminders, and success analytics through controlled workflows.",primaryCta:"Modernize Your Student Experience",products:["AI enrollment receptionist","Student information portal","Course-registration application","Virtual tutoring assistant","Learning-management integration","Parent communication portal","Attendance monitoring","Student-support ticketing","Tuition and payment reminders","Class scheduling","Multilingual admissions intake","Student-success analytics","Corporate training platform"],intake:["Institution type","Student and campus count","Monthly inquiries","Current student system"],actions:["Answer admissions questions","Qualify prospective students","Schedule campus visits","Register course interest","Send application reminders","Route students to advisors","Track incomplete enrollment","Generate advisor activities","Synchronize approved applicants with Odoo"],qualifyingQuestions:["Institution type","Number of students","Number of campuses","Monthly inquiries","Current student system","Required languages","Online-learning requirements","Enrollment challenge"],disclosures:["Student records require controlled access and retention.","Age-appropriate consent is required.","Academic decisions require human review.","AI does not issue final grades or disciplinary decisions without authorized review."]}),
  build({slug:"dental-ai",campaign:"DENTAL_AI",name:"Dental practices",category:"Healthcare and Care",eyebrow:"AI for Dental Practices",headline:"Fill Your Schedule Without Missing Patient Calls",summary:"Coordinate appointments, recalls, new-patient intake, cancellation waitlists, approved reminders, and staff escalation.",primaryCta:"Build Your Dental Patient System",products:["Dental AI receptionist","Appointment-booking portal","Recall and cleaning reminders","Treatment follow-up workflows","New-patient intake","Insurance-information collection","Cancellation waitlist","Secure document portal","Video-consultation requests","Patient communication dashboard"],intake:["Practice size","Locations","Monthly appointments","Current practice system"],actions:["Schedule and reschedule visits","Fill canceled appointments","Send approved treatment reminders","Route emergencies to staff","Collect preliminary insurance information","Send intake forms","Request post-visit feedback","Track advertising-source conversion"],qualifyingQuestions:["Practice size","Providers","Locations","Monthly calls","Current practice system","Insurance workflow","Recall volume","Required languages"],disclosures:["AI does not diagnose or prescribe.","Clinical decisions require dental professionals.","Healthcare compliance is not claimed without verified evidence."]}),
  build({slug:"veterinary-ai",campaign:"VETERINARY_AI",name:"Veterinary practices",category:"Healthcare and Care",eyebrow:"AI for Veterinary Practices",headline:"Help Pet Owners Reach Your Practice Anytime",summary:"Support pet-owner intake, routine scheduling, vaccination reminders, boarding, refill routing, and emergency human escalation.",primaryCta:"Improve Your Pet-Owner Experience",products:["Veterinary AI receptionist","Pet-owner portal","Appointment scheduling","Vaccination reminders","Prescription-refill request routing","Pet intake and history forms","Emergency-call escalation","Boarding reservation system","Follow-up communication","Multi-location routing"],intake:["Animal and service type","New or existing client","Preferred location","Urgency statement"],actions:["Identify animal and service type","Book routine visits","Route emergency statements","Send vaccination reminders","Collect pre-visit information","Schedule grooming or boarding","Notify staff about refill requests","Track missed appointments"],qualifyingQuestions:["Practice type","Veterinarians","Locations","Monthly visits","Current practice system","Boarding or grooming","Reminder needs","Emergency workflow"],disclosures:["AI does not independently diagnose animals.","AI does not prescribe or change medication.","Emergency and medical decisions require veterinary review."]}),
  build({slug:"automotive-ai",campaign:"AUTOMOTIVE_AI",name:"Automotive dealerships and repair",category:"Commerce and Hospitality",eyebrow:"AI for Automotive Businesses",headline:"Turn Vehicle Inquiries Into Appointments and Sales",summary:"Connect buyer qualification, inventory questions, test drives, service appointments, repair status, parts inquiries, and CRM follow-up.",primaryCta:"Automate Your Automotive Operations",products:["Dealership AI receptionist","Repair-shop AI receptionist","Service appointment scheduler","Vehicle inventory assistant","Test-drive scheduler","Estimate-request portal","Repair-status application","Parts availability assistant","Customer follow-up system","Dealer CRM integration"],intake:["Dealership or repair shop","Vehicle or service interest","Location","Preferred appointment"],actions:["Qualify vehicle buyers","Schedule test drives","Capture trade-in information","Book service visits","Send maintenance reminders","Notify repair status","Route parts inquiries","Follow up on unsold leads","Create Odoo opportunities","Track campaign conversion"],qualifyingQuestions:["Dealership or repair shop","Number of locations","Monthly calls","Monthly repair orders","Vehicle inventory size","Current dealer-management system","Required integrations"]}),
  build({slug:"restaurant-ai",campaign:"RESTAURANT_AI",name:"Restaurants and food service",category:"Commerce and Hospitality",eyebrow:"AI for Restaurants and Food Service",headline:"Serve More Customers Without Missing Orders or Reservations",summary:"Coordinate reservations, approved menu questions, takeout, catering, loyalty, delivery, purchasing, schedules, and multi-location reporting.",primaryCta:"Automate Your Guest and Order Experience",products:["Restaurant AI receptionist","Reservation assistant","Takeout-order assistant","Catering-request portal","Digital menu","Customer loyalty application","Delivery coordination","Inventory and purchasing dashboard","Employee scheduling","Multi-location reporting"],intake:["Location","Reservation, order, or catering intent","Party or order size","Timing"],actions:["Answer menu and opening-hour questions","Make reservation requests","Collect catering inquiries","Provide approved allergen information","Send order confirmations","Route large-event requests","Collect feedback","Create catering opportunities in Odoo"],qualifyingQuestions:["Restaurant type","Locations","Monthly reservations","Order volume","Current POS","Delivery systems","Catering volume","Required integrations"],disclosures:["Allergen information comes only from controlled sources.","AI does not invent ingredient or safety information.","Staff review complex allergy requests."]}),
  build({slug:"manufacturing-ai",campaign:"MANUFACTURING_AI",name:"Manufacturing",category:"Agriculture and Production",eyebrow:"AI for Manufacturing",headline:"Connect Production, Quality and Customer Operations",summary:"Connect production monitoring, maintenance, quality, suppliers, inventory, work orders, safety reporting, customer orders, and Odoo middleware.",primaryCta:"Build Your Intelligent Manufacturing System",products:["Production monitoring dashboard","Maintenance-request system","Predictive-maintenance support","Quality-control workflow","Supplier portal","Purchase-request automation","Inventory monitoring","Work-order application","Safety-incident reporting","Customer-order portal","Odoo manufacturing middleware"],intake:["Manufacturing type","Facilities","Production volume","Current ERP"],actions:["Create maintenance work orders","Detect production exceptions","Route quality incidents","Extract supplier documents","Monitor stock thresholds","Notify late orders","Summarize shift reports","Track downtime","Synchronize Odoo manufacturing records"],qualifyingQuestions:["Manufacturing type","Number of facilities","Production volume","Current ERP","Equipment count","Primary downtime causes","Data sources","Required integrations"]}),
  build({slug:"recruitment-ai",campaign:"RECRUITMENT_AI",name:"Recruitment and human resources",category:"Professional Services",eyebrow:"AI for Recruitment and Human Resources",headline:"Move Qualified Candidates Through Hiring Faster",summary:"Coordinate candidate intake, interviews, communication, onboarding, employee support, training, workforce analytics, and Odoo recruitment.",primaryCta:"Improve Your Hiring Workflow",products:["Recruitment AI receptionist","Career portal","Applicant intake","Interview scheduler","Candidate communication system","Onboarding portal","Employee help desk","Training and policy assistant","Workforce analytics","Odoo recruitment integration"],intake:["Open position","Candidate stage","Preferred interview time","Missing documents"],actions:["Answer job questions","Collect applications","Schedule interviews","Send status notifications","Route candidates by position","Request missing documents","Generate recruiter activities","Coordinate onboarding","Track hiring-source performance"],qualifyingQuestions:["Company size","Monthly applicants","Open roles","Recruiters","Current ATS","Interview workflow","Onboarding needs","Required integrations"],disclosures:["Protected characteristics are not used for scoring.","AI does not make final hiring or termination decisions.","Human review, explainable criteria, and recommendation audits are required."]}),
  build({slug:"nonprofit-ai",campaign:"NONPROFIT_AI",name:"Nonprofits and community organizations",category:"Public and Community Services",eyebrow:"AI for Nonprofits and Community Organizations",headline:"Serve More People With Connected Digital Operations",summary:"Connect community information, donors, volunteers, programs, grants, events, beneficiary intake, communications, and impact reporting.",primaryCta:"Expand Your Organization’s Impact",products:["Community-services AI receptionist","Donor portal","Volunteer-management system","Program registration","Grant tracking","Event registration","Beneficiary intake","Multilingual information assistant","Donation communication","Impact dashboard"],intake:["Program or service","Volunteer or donor intent","Location","Preferred language"],actions:["Answer program questions","Register volunteers","Schedule orientations","Capture donor inquiries","Send event reminders","Route service requests","Track grant deadlines","Generate follow-up activities","Produce impact reports","Synchronize contacts with Odoo"],qualifyingQuestions:["Organization type","Programs","Monthly inquiries","Volunteers","Current donor system","Events","Languages","Reporting needs"],disclosures:["Beneficiary information requires minimized collection, controlled access, and retention.","Protected service recipients are excluded from analytics."]}),
  build({slug:"public-services-ai",campaign:"PUBLIC_SERVICES_AI",name:"Government and public services",category:"Public and Community Services",eyebrow:"AI for Public Services",headline:"Make Public Information and Services Easier to Access",summary:"Connect approved public information, citizen services, appointments, permits, requests, notifications, records, complaints, and operational dashboards.",primaryCta:"Modernize Public-Service Delivery",products:["Public-information AI receptionist","Citizen-service portal","Appointment system","Permit and license intake","Service-request tracking","Multilingual information assistant","Emergency-notification workflow","Public records request portal","Complaint and feedback system","Operational dashboard"],intake:["Agency or department","Service requested","Location","Accessibility or language need"],actions:["Answer approved public questions","Route requests by agency","Schedule appointments","Collect application information","Notify residents about status","Track unresolved requests","Escalate urgent public-safety statements","Generate department work queues"],qualifyingQuestions:["Agency type","Departments","Population served","Monthly requests","Current case system","Languages","Accessibility needs","Required integrations"],disclosures:["Legal eligibility and adverse decisions require authorized human review.","Accessible alternatives, public-record retention, and identity protection are required."]}),
  build({slug:"energy-ai",campaign:"ENERGY_AI",name:"Energy, solar and utilities",category:"Operations and Infrastructure",eyebrow:"AI for Energy, Solar and Utilities",headline:"Connect Customer Service, Field Work and Energy Operations",summary:"Coordinate solar qualification, outage reporting, field dispatch, installations, meter data, maintenance, billing routing, sales, and operations.",primaryCta:"Build Your Connected Energy Platform",products:["Utility AI receptionist","Solar lead-qualification assistant","Outage-reporting portal","Field-service dispatch","Installation scheduler","Customer energy dashboard","Meter-data integration","Maintenance application","Billing-inquiry routing","Sales and operations CRM"],intake:["Utility or solar request","Service location","Project or outage context","Preferred follow-up"],actions:["Qualify solar prospects","Estimate preliminary requirements","Schedule site assessments","Receive outage reports","Route emergency statements","Dispatch field personnel","Send installation updates","Create Odoo sales opportunities","Track renewable campaigns"],qualifyingQuestions:["Business type","Service territory","Monthly inquiries","Field teams","Current CRM","Meter or monitoring systems","Installation volume","Required integrations"],disclosures:["Savings and production results are not promised without validated calculations.","Hazardous conditions require immediate approved escalation.","Authorized humans control field operations."]}),
  build({slug:"telecom-it-ai",campaign:"TELECOM_IT_AI",name:"Telecommunications and managed IT",category:"Technology and Media",eyebrow:"AI for Telecom and Managed IT",headline:"Resolve Requests Faster and Keep Customers Connected",summary:"Connect support intake, ticket routing, service status, installations, network incidents, knowledge, SLA monitoring, subscriptions, and renewals.",primaryCta:"Modernize Your Support Operations",products:["Technical-support AI receptionist","Customer support portal","Ticket intake and routing","Service-status dashboard","Installation scheduler","Network incident workflow","Remote-support request system","Knowledge assistant","SLA monitoring","Subscription and renewal automation"],intake:["Service and account type","Support intent","Impact and severity","Preferred contact"],actions:["Identify service and account type","Classify support intent","Create support tickets","Route incidents by severity","Schedule installation","Send outage updates","Escalate SLA risks","Summarize support calls","Synchronize Odoo customers and opportunities"],qualifyingQuestions:["Provider type","Customers","Monthly tickets","Support teams","Current ticketing system","Network tools","SLA tiers","Required integrations"]}),
  build({slug:"wellness-ai",campaign:"WELLNESS_AI",name:"Beauty, wellness and fitness",category:"Healthcare and Care",eyebrow:"AI for Beauty, Wellness and Fitness",headline:"Keep Your Schedule Full and Your Clients Engaged",summary:"Coordinate appointments, classes, memberships, training, reminders, waitlists, loyalty, subscriptions, communications, and multi-location analytics.",primaryCta:"Grow Your Wellness Business",products:["Salon or gym AI receptionist","Appointment and class booking","Membership portal","Personal-training scheduler","Treatment and service reminders","Cancellation waitlist","Loyalty application","Package and subscription management","Client communication","Multi-location analytics"],intake:["Service or class","Location","Preferred time","Membership status"],actions:["Book appointments and classes","Fill cancellations","Send reminders","Promote approved services","Track membership inquiries","Route treatment questions to qualified staff","Collect feedback","Follow up with inactive clients","Create Odoo sales opportunities"],qualifyingQuestions:["Business type","Locations","Monthly bookings","Members","Current booking system","Classes or treatments","Waitlist needs","Required integrations"],disclosures:["AI does not provide unapproved medical or treatment advice.","Health-related questions route to qualified professionals."]}),
  build({slug:"security-services-ai",campaign:"SECURITY_SERVICES_AI",name:"Security and alarm companies",category:"Operations and Infrastructure",eyebrow:"AI for Security Service Companies",headline:"Respond Faster From Sales Inquiry to Service Dispatch",summary:"Connect prospect qualification, alarm-service intake, installations, dispatch, customer access, incidents, guards, equipment, renewals, and reporting.",primaryCta:"Connect Your Security Operations",products:["Security-company AI receptionist","Alarm-service intake","Installation scheduler","Technician dispatch","Customer portal","Incident-reporting application","Guard scheduling","Equipment inventory","Contract-renewal automation","Sales and service dashboard"],intake:["Sales or service request","Property type","Location","Urgency boundary"],actions:["Qualify security prospects","Schedule property assessments","Route service requests","Identify urgent alarm issues","Dispatch authorized technicians","Send installation updates","Create incident records","Track contract renewals","Create Odoo opportunities and activities"],qualifyingQuestions:["Service type","Locations","Monthly calls","Technicians or guards","Current dispatch system","Alarm platforms","Renewal volume","Required integrations"],disclosures:["AI cannot disable alarms or controls without authenticated authorization.","Emergency events require approved escalation.","Property-security details are excluded from analytics."]}),
  build({slug:"marketing-media-ai",campaign:"MARKETING_MEDIA_AI",name:"Marketing agencies and media",category:"Technology and Media",eyebrow:"AI for Marketing Agencies and Media Teams",headline:"Create, Approve and Measure Campaigns Faster",summary:"Connect agency lead intake, client portals, campaign requests, content, approvals, publishing, assets, reporting, partners, and proposals.",primaryCta:"Automate Your Agency Workflow",products:["Agency lead receptionist","Client portal","Campaign request system","Content workflow","Approval portal","Social publishing integration","Creative asset library","Reporting dashboard","Influencer and partner CRM","Proposal automation"],intake:["Campaign or project type","Channels","Timeline","Approval owners"],actions:["Qualify prospective clients","Collect campaign briefs","Assign creative tasks","Route content for approval","Schedule approved content","Generate performance summaries","Track client feedback","Monitor deadlines","Create Odoo opportunities and projects"],qualifyingQuestions:["Agency type","Clients","Monthly campaigns","Team size","Current project system","Publishing tools","Approval process","Required integrations"],disclosures:["External publication requires approval.","Client assets, copyright, and usage rights must be protected.","AI does not publish misleading claims."]}),
  build({slug:"gaming-entertainment-ai",campaign:"GAMING_ENTERTAINMENT_AI",name:"Gaming and entertainment",category:"Technology and Media",eyebrow:"AI for Gaming and Entertainment",headline:"Create Better Player and Audience Experiences",summary:"Connect player support, ticketing, events, communities, recommendations, tournaments, loyalty, moderation, partners, and engagement analytics.",primaryCta:"Build Your Entertainment Platform",products:["Player-support AI receptionist","Customer-service portal","Event and ticketing platform","Community-management tools","Content recommendation","Tournament registration","Loyalty and rewards platform","Moderation workflow","Creator and partner portal","Engagement analytics"],intake:["Player, attendee, or partner intent","Event or product","Account boundary","Preferred follow-up"],actions:["Answer event and account questions","Create support tickets","Route technical issues","Register players or attendees","Send event reminders","Monitor approved community signals","Route moderation decisions for review","Track campaign and ticket conversion","Synchronize partnerships and sales with Odoo"],qualifyingQuestions:["Entertainment type","Audience size","Monthly tickets","Events","Current support system","Community platforms","Age ranges","Required integrations"],disclosures:["Age-appropriate controls are required.","Account sanctions require human review.","Chance-based outcomes are not guaranteed.","Jurisdiction-specific rules apply where gaming is regulated."]}),
];
