import { expansionIndustryConfigs } from "./industryConfigExpansion";

export type IndustryConfig = {
  slug: string;
  campaign: string;
  name: string;
  eyebrow: string;
  headline: string;
  summary: string;
  problems: string[];
  intake: string[];
  actions: string[];
  routing: string[];
  integrations: { name: string; status: "Supported" | "Planned" }[];
  scenarios: { title: string; transcript: string; outcome: string }[];
  faq: [string, string][];
  qualifyingQuestions: string[];
  disclosures?: string[];
  products?: string[];
  category?: string;
  primaryCta?: string;
};

export const logisticsIndustry: IndustryConfig = {
  slug: "logistics-ai",
  campaign: "LOGISTICS_AI",
  name: "Transportation and logistics",
  eyebrow: "Codestra Logistics AI",
  headline: "Keep Every Shipment Conversation Moving",
  summary:
    "Capture shipping quote requests, pickup details, customer and carrier information, callback needs, and routing context around the clock.",
  problems: [
    "Quote requests arrive while sales teams are handling active shipments.",
    "Callers repeat origin, destination, equipment, and timing details after transfers.",
    "After-hours inquiries can wait until the next business day.",
    "Customer and carrier conversations are difficult to attribute across systems.",
  ],
  intake: ["Origin and destination", "Shipment type and equipment", "Pickup date", "Customer or carrier identity"],
  actions: ["Prepare a quote request", "Request a pickup", "Create a callback activity", "Synchronize an approved Odoo lead"],
  routing: ["Sales office", "Dispatch or terminal", "Customer service", "Urgent human escalation"],
  integrations: [
    { name: "Odoo CRM", status: "Supported" },
    { name: "n8n", status: "Supported" },
    { name: "Google Calendar", status: "Supported" },
    { name: "VICIdial", status: "Planned" },
    { name: "Microsoft Outlook", status: "Planned" },
    { name: "Transportation management systems", status: "Planned" },
  ],
  scenarios: [
    { title: "Shipping quote", transcript: "Caller provides Miami origin, Dallas destination, pallet count, weight, and pickup date.", outcome: "Qualified quote request prepared for the sales queue." },
    { title: "Pickup scheduling", transcript: "Customer confirms account, location, freight type, dock hours, and preferred pickup window.", outcome: "Pickup request prepared for dispatch review." },
    { title: "After-hours callback", transcript: "Carrier requests a callback about an urgent next-day load.", outcome: "Urgency and callback context queued for a human operator." },
  ],
  faq: [
    ["Can Codestra replace our current telephone number?", "The approved implementation can normally use forwarding or provider routing so the existing public number remains unchanged."],
    ["Can it create freight quotes automatically?", "It can collect and validate required inputs. Final pricing and quote release remain within approved business rules and human controls."],
    ["Can calls route by terminal or office?", "Yes. Routing can use location, department, language, caller type, operating hours, intent, and urgency."],
    ["Does it connect to Odoo?", "The controlled middleware supports Odoo lead delivery. Each field, campaign, team, and owner mapping is confirmed in staging before live writes."],
    ["Is the demonstration real activity?", "No. All demonstrations and figures on this page are clearly labeled simulations or sample data."],
  ],
  qualifyingQuestions: ["Business type", "Shipper, carrier, broker, or logistics provider", "Monthly shipments", "Fleet size", "Current CRM or TMS", "Dispatchers", "Required integrations", "Primary operational problem"],
};

const make = (config: IndustryConfig) => config;
export const industryConfigs: IndustryConfig[] = [logisticsIndustry,
make({slug:"legal-ai",campaign:"LEGAL_AI",name:"Law firms and legal services",eyebrow:"Codestra Legal AI",headline:"Capture Every Potential Client—Day or Night",summary:"Qualify prospective clients, schedule consultations, route practice-area inquiries, and preserve human review boundaries.",problems:["Potential clients call after hours","Intake details arrive inconsistently","Practice-area routing interrupts legal teams","Multilingual inquiries need reliable follow-up"],intake:["Practice area","Conflict-check identifiers","Consultation preference","Required language"],actions:["Legal AI receptionist","Prospective-client intake","Consultation scheduling","Secure document collection","Call summaries","Case-management integration"],routing:["Practice-area team","Intake specialist","Authorized attorney review","After-hours callback"],integrations:[{name:"Odoo CRM",status:"Supported"},{name:"Calendars",status:"Supported"},{name:"Case-management systems",status:"Planned"}],scenarios:[{title:"After-hours inquiry",transcript:"A prospective client describes the general matter and preferred contact time.",outcome:"Preliminary intake prepared for authorized review."},{title:"Consultation request",transcript:"Caller selects a practice area, office, language, and available time.",outcome:"Consultation request queued without legal advice."},{title:"Document follow-up",transcript:"The system explains an approved secure document-request process.",outcome:"Human-controlled collection task prepared."}],faq:[["Does the AI give legal advice?","No. It performs approved administrative intake and routing only."],["Can it promise an outcome?","No. It never promises case acceptance or outcomes."],["Who reviews substantive responses?","An authorized human legal professional."],["Can it route by practice area?","Yes, using approved intake and routing rules."],["Are demonstrations real client matters?","No. They are simulations."]],qualifyingQuestions:["Law-firm size","Practice areas","Monthly inquiries","Offices","Current case-management system","Languages","After-hours coverage","Consultation booking"],disclosures:["AI does not provide legal advice.","AI does not promise case outcomes.","Substantive legal responses require authorized human review."]}),
make({slug:"healthcare-ai",campaign:"HEALTHCARE_AI",name:"Private healthcare",eyebrow:"Codestra Healthcare AI",headline:"Give Patients Secure, Convenient Access to Your Practice",summary:"Support approved scheduling, intake, referrals, reminders, and multilingual communication with clinical decisions reserved for authorized professionals.",problems:["Scheduling demand overwhelms staff","Patient access varies by channel","Referral follow-up is fragmented","Routine reminders consume clinical time"],intake:["Practice type","Provider or location","Appointment request","Preferred language"],actions:["Medical-practice receptionist","Private patient portal","Secure video appointment workflow","Referral and refill-request routing","Approved reminders"],routing:["Scheduling","Referral team","Clinical review","Urgent human escalation"],integrations:[{name:"Odoo CRM",status:"Supported"},{name:"Calendars",status:"Supported"},{name:"Practice-management systems",status:"Planned"}],scenarios:[{title:"Appointment request",transcript:"Patient requests a visit type, provider, location, and preferred time.",outcome:"Scheduling request prepared for approved availability review."},{title:"Referral status",transcript:"Caller requests an update using a controlled identity-verification boundary.",outcome:"Referral follow-up routed to staff."},{title:"Refill request",transcript:"Patient submits an administrative refill request.",outcome:"Request routed for authorized clinical review."}],faq:[["Can the AI diagnose?","No."],["Can it prescribe medication?","No."],["Is compliance claimed?","No compliance claim is made until formally verified."],["Can it support video visits?","It can coordinate an approved secure workflow."],["Are demonstrations patient activity?","No. They are simulations."]],qualifyingQuestions:["Practice type","Providers","Locations","Monthly appointments","Practice-management system","Video consultation","Reminder requirements","Languages"],disclosures:["AI does not independently diagnose.","AI does not prescribe or change medications.","Medical decisions require authorized clinical review.","Healthcare compliance is not claimed until formally verified."]}),
make({slug:"senior-care-ai",campaign:"SENIOR_CARE_AI",name:"Senior care and medical transportation",eyebrow:"Codestra Senior Care AI",headline:"Coordinate Care, Transportation and Family Communication",summary:"Coordinate ride requests, recurring trips, caregiver updates, accessibility intake, and controlled family notifications.",problems:["Recurring transportation requires repetitive coordination","Families need timely nonclinical updates","Accessibility needs must follow each trip","Authorizations span multiple teams"],intake:["Service or trip type","Accessibility needs","Recurring schedule","Authorization status"],actions:["Senior-service receptionist","Medical transportation portal","Ride scheduling","Caregiver communication","Family notifications","Driver tracking"],routing:["Transportation desk","Care coordinator","Authorization team","Human escalation"],integrations:[{name:"Odoo CRM",status:"Supported"},{name:"GPS providers",status:"Planned"},{name:"n8n",status:"Supported"}],scenarios:[{title:"Recurring ride",transcript:"Family requests recurring accessible transportation.",outcome:"Schedule request prepared for authorization review."},{title:"Family update",transcript:"Family member requests an approved trip-status update.",outcome:"Notification workflow prepared."},{title:"Driver escalation",transcript:"Driver reports an operational delay.",outcome:"Dispatch escalation routed with context."}],faq:[["Does this replace caregivers?","No."],["Can it schedule recurring trips?","Yes, subject to approval."],["Can families receive updates?","Yes, using configured consent rules."],["Does it make medical decisions?","No."],["Is GPS live?","Only after an approved integration."]],qualifyingQuestions:["Service type","Monthly rides","Fleet size","Accessibility needs","Recurring trips","Current dispatch system","Family notification needs","Authorization workflow"]}),
make({slug:"real-estate-ai",campaign:"REAL_ESTATE_AI",name:"Real estate and property management",eyebrow:"Codestra Real Estate AI",headline:"Convert More Property Inquiries Into Appointments",summary:"Qualify buyers, renters, and sellers; schedule showings; route maintenance; and synchronize approved Odoo opportunities.",problems:["Property interest cools quickly","Agents repeat qualification questions","Showing coordination crosses calendars","Maintenance calls need structured routing"],intake:["Buyer, renter, or seller","Location and budget","Timeline","Property or maintenance context"],actions:["Real-estate receptionist","Property assistant","Showing scheduler","Tenant portal","Maintenance requests","Lead distribution"],routing:["Listing agent","Buyer team","Property management","Maintenance vendor"],integrations:[{name:"Odoo CRM",status:"Supported"},{name:"Calendars",status:"Supported"},{name:"Listing platforms",status:"Planned"}],scenarios:[{title:"Buyer inquiry",transcript:"Buyer provides budget, location, property type, and timeframe.",outcome:"Qualified showing request prepared."},{title:"Seller consultation",transcript:"Owner requests a valuation consultation.",outcome:"Seller lead routed by territory."},{title:"Maintenance request",transcript:"Tenant describes category and urgency without sensitive detail.",outcome:"Work request routed to property management."}],faq:[["Can it schedule showings?","Yes, through approved calendars."],["Can it assign agents?","Yes, using configured rules."],["Does it value properties?","It does not make binding valuations."],["Can it update Odoo?","Only after staging approval."],["Are listings live?","Only with an approved integration."]],qualifyingQuestions:["Portfolio type","Agents","Monthly inquiries","Locations","Current CRM","Listing systems","Showing volume","Maintenance workflow"]}),
make({slug:"financial-services-ai",campaign:"FINANCIAL_AI",name:"Financial services and insurance",eyebrow:"Codestra Financial Services AI",headline:"Respond Faster While Keeping Financial Workflows Controlled",summary:"Coordinate preliminary intake, onboarding, secure document requests, status inquiries, renewals, and advisor scheduling.",problems:["Status calls interrupt advisors","Onboarding documents arrive across channels","Renewal conversations need timely follow-up","Regulated decisions require controlled handoffs"],intake:["Service requested","Customer status","Advisor preference","Secure follow-up requirement"],actions:["Financial-services receptionist","Preliminary intake","Secure document collection","Customer onboarding","Application status","Policy renewal"],routing:["Advisor team","Licensed professional","Operations","Compliance review"],integrations:[{name:"Odoo CRM",status:"Supported"},{name:"Secure document systems",status:"Planned"},{name:"Calendars",status:"Supported"}],scenarios:[{title:"Advisor appointment",transcript:"Customer requests a consultation and preferred language.",outcome:"Advisor scheduling request prepared."},{title:"Application status",transcript:"Customer requests an update through an identity-verification boundary.",outcome:"Status request routed to authorized staff."},{title:"Renewal inquiry",transcript:"Policyholder requests a renewal discussion.",outcome:"Licensed team follow-up prepared."}],faq:[["Does AI approve applications?","No."],["Can it make regulated decisions?","No."],["Is financial data sent to analytics?","No."],["Can documents be collected?","Only through an approved secure system."],["Who reviews recommendations?","Authorized human professionals."]],qualifyingQuestions:["Business type","Advisors or agents","Monthly inquiries","Products","Current CRM","Document workflow","Languages","Regulatory review needs"],disclosures:["AI does not promise approval.","Regulated decisions require authorized human review.","Sensitive financial data does not enter marketing analytics."]}),
make({slug:"ecommerce-ai",campaign:"ECOMMERCE_AI",name:"Retail and e-commerce",eyebrow:"Codestra E-Commerce AI",headline:"Turn Product Questions Into Completed Orders",summary:"Help shoppers find products, check orders, manage approved returns, receive inventory notices, and reconnect abandoned carts.",problems:["Product questions delay purchases","Order-status demand burdens support","Returns need consistent policy handling","Inventory interest is lost when items sell out"],intake:["Product or order intent","Catalog preferences","Order reference boundary","Preferred resolution"],actions:["AI shopping assistant","Product recommendations","Order status","Returns workflows","Inventory notifications","Abandoned-cart automation","Upsell opportunities"],routing:["Sales","Order support","Returns","Human specialist"],integrations:[{name:"Odoo",status:"Supported"},{name:"Shopify",status:"Planned"},{name:"n8n",status:"Supported"}],scenarios:[{title:"Product discovery",transcript:"Shopper describes use, budget, and preferences.",outcome:"Approved catalog options presented."},{title:"Order status",transcript:"Customer requests status through an order-verification boundary.",outcome:"Approved status workflow initiated."},{title:"Return request",transcript:"Customer selects an approved return reason.",outcome:"Return workflow prepared under policy."}],faq:[["Can it recommend products?","Yes, from approved catalog data."],["Can it issue refunds?","Only if explicitly authorized and tested."],["Does it integrate with Shopify?","Planned per implementation."],["Can it update Odoo?","After staging approval."],["Are conversion claims guaranteed?","No."]],qualifyingQuestions:["Store platform","Monthly orders","Catalog size","Support volume","Current ERP","Returns workflow","Languages","Required integrations"]}),
make({slug:"hospitality-ai",campaign:"HOSPITALITY_AI",name:"Hotels, travel and hospitality",eyebrow:"Codestra Hospitality AI",headline:"Serve Every Guest Before, During and After Their Stay",summary:"Coordinate reservations, digital check-in, guest requests, concierge services, transportation, activities, notifications, and feedback.",problems:["Guest requests arrive around the clock","Front desks repeat reservation questions","Service orders span multiple departments","Feedback arrives too late to recover issues"],intake:["Property and dates","Reservation status","Guest request","Preferred language"],actions:["Hotel AI receptionist","Reservation assistant","Guest application","Digital check-in","Room-service ordering","Concierge assistant","Feedback collection"],routing:["Reservations","Front desk","Food and beverage","Guest services"],integrations:[{name:"Odoo",status:"Supported"},{name:"Calendars",status:"Supported"},{name:"Property-management systems",status:"Planned"}],scenarios:[{title:"Reservation inquiry",transcript:"Guest requests dates, room preferences, and amenities.",outcome:"Reservation request prepared."},{title:"Guest service",transcript:"Guest requests transportation and an activity.",outcome:"Concierge tasks routed."},{title:"Stay feedback",transcript:"Guest reports a service concern.",outcome:"Human recovery workflow escalated."}],faq:[["Can it confirm reservations?","Only through an approved PMS connection."],["Can guests switch languages?","Configured supported languages can be enabled."],["Can it order room service?","Under approved menus and workflows."],["Does it replace staff?","No, it supports staff."],["Are sample stays real?","No."]],qualifyingQuestions:["Property type","Rooms","Locations","Monthly reservations","Current PMS","Guest services","Languages","Required integrations"]}),
make({slug:"construction-ai",campaign:"CONSTRUCTION_AI",name:"Construction and home services",eyebrow:"Codestra Construction AI",headline:"Turn Service Calls Into Scheduled Jobs",summary:"Capture estimates, schedule inspections, dispatch technicians, coordinate field applications, and follow up on projects.",problems:["Crews cannot answer every call","Estimate details arrive incomplete","Dispatch changes throughout the day","Project photos and documents scatter across systems"],intake:["Service type","Project location","Urgency","Estimate or inspection request"],actions:["Contractor AI receptionist","Estimate requests","Inspection scheduling","Technician dispatch","Field-service application","Customer project portal","Inventory tracking"],routing:["Estimator","Dispatcher","Project manager","Emergency human escalation"],integrations:[{name:"Odoo",status:"Supported"},{name:"n8n",status:"Supported"},{name:"Field-service systems",status:"Planned"}],scenarios:[{title:"Estimate request",transcript:"Homeowner provides service, property, timing, and contact details.",outcome:"Estimate request routed by territory."},{title:"Inspection scheduling",transcript:"Customer selects an approved inspection window.",outcome:"Scheduling request prepared."},{title:"Technician dispatch",transcript:"Urgent service category and location are captured.",outcome:"Human dispatcher alerted with context."}],faq:[["Can it price jobs?","It can collect inputs; final estimates follow approved rules."],["Can it dispatch technicians?","Only through approved workflows."],["Can customers upload photos?","A secure upload system can be scoped."],["Can it track inventory?","Through an approved integration."],["Are response times guaranteed?","No public SLA is claimed."]],qualifyingQuestions:["Trade or service","Technicians","Monthly calls","Service area","Current field system","Dispatchers","Emergency workflow","Required integrations"]}),
make({slug:"agriculture-ai",campaign:"AGRICULTURE_AI",name:"Agriculture and food production",eyebrow:"Codestra Agriculture AI",headline:"Make Faster Decisions Across Your Farm and Supply Chain",summary:"Coordinate crop plans, irrigation observations, inventories, worker tasks, produce sales, buyer relationships, pest reports, and profitability dashboards.",problems:["Operational data remains in separate records","Seasonal tasks depend on timely coordination","Input inventory is difficult to forecast","Buyer and production planning are disconnected"],intake:["Operation type","Acreage or production scale","Crop or product","Primary planning challenge"],actions:["Farm-management platform","Crop planning","Planting and harvest scheduling","Irrigation monitoring","Input inventory","Worker tasks","Buyer CRM","Pest reporting"],routing:["Farm manager","Field team","Sales","Qualified agronomy review"],integrations:[{name:"Odoo",status:"Supported"},{name:"Sensor platforms",status:"Planned"},{name:"n8n",status:"Supported"}],scenarios:[{title:"Crop plan",transcript:"Manager selects fields, crop, target dates, and resource constraints.",outcome:"Planning workflow prepared."},{title:"Pest report",transcript:"Worker records an observation and optional approved image workflow.",outcome:"Decision-support report routed for expert review."},{title:"Buyer inquiry",transcript:"Buyer requests product, quantity, grade, and delivery timing.",outcome:"Qualified sales inquiry prepared."}],faq:[["Does image analysis guarantee a diagnosis?","No. It is decision support only."],["Can it monitor irrigation?","With approved sensor integrations."],["Can it track profitability?","Using configured cost and production data."],["Can workers receive tasks?","Yes, through an approved application."],["Can it update Odoo?","After staging mapping and approval."]],qualifyingQuestions:["Operation type","Acreage","Crops or products","Workers","Current software","Sensor systems","Buyer volume","Primary operational problem"],disclosures:["Image-based crop analysis is decision support and not a guaranteed diagnosis."]}),
...expansionIndustryConfigs];
export const plannedIndustries = industryConfigs.slice(1).map(({slug,name}) => [slug,name] as const);
export const industryBySlug = Object.fromEntries(industryConfigs.map((item) => [item.slug, item]));
