# Generated by Django 5.1.4 on 2025-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
