# Generated by Django 5.1.4 on 2025-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='extra-fields'),
        ),
    ]
