# Generated by Django 5.2.16 on 2026-08-02 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_casestudy_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicBillingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=64)),
                ('uses_erp', models.BooleanField()),
                ('consent_to_contact', models.BooleanField()),
                ('source', models.CharField(default='electronic-billing', max_length=64)),
                ('odoo_sync_status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('odoo_record_id', models.CharField(blank=True, max_length=128)),
                ('odoo_last_error', models.TextField(blank=True)),
                ('odoo_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='odoo_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='odoo_record_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contactus',
            name='odoo_sync_status',
            field=models.CharField(db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='contactus',
            name='odoo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
