# Generated by Django 5.2.16 on 2026-08-02 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_electronicbillinginterest_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='odoo_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='odoo_record_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='odoo_sync_status',
            field=models.CharField(db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='odoo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
